### ISSUE TITLE
Port to material-ui 1.0.0-beta

### ISSUE THREAD

**Issue by pedrost** [TeamWertarbyte/material-auto-rotating-carousel#25]
So, im getting 
Module not found: Can't resolve 'material-ui/svg-icons/navigation/arrow-back' in 'C:\Users\Pedro\tt\node_modules\material-auto-rotating-carousel\lib'

I'm using material-ui last version, should i use a previous one?

**Comment by leMaik** [comment]
Unfortunately, this component is not yet ported to material-ui v1-beta :cry: We'll port it soon, but for now, you'll need material-ui v0.19 (or any other version < 1.0.0).

**Comment by leMaik** [comment]
Good news, I'm on it! :tada:

**Comment by leMaik** [comment]
Done! :tada: `npm i --save material-auto-rotating-carousel@next`. Docs are here on the `next` branch, let me know what you think. :+1:

**Comment by gpdeedler** [comment]
Hi . Thank you for updating this!  The 2.0.0 version package.json uses 
"@material-ui/core": "^1.0.0",
"@material-ui/icons": "^1.0.0"

Which uses the newest version of material-ui but NOT the newest approach of using material-ui-icons.

This new one updates to the newest material-ui-icons which is good but seems to roll back to "material-ui": "^1.0.0-beta.38" instead of "@material-ui/core": "^1.0.0".

**Comment by leMaik** [comment]
@gpdeedler I don't know what you mean. Using ^1.0.0 for both is exactly what I intended to do and how both packages are meant to be used. Also, @material-ui/icons ^1.0.0 [does not](https://github.com/mui-org/material-ui/blob/master/packages/material-ui-icons/package.json#L39) roll back anything… it depends on @material-ui/core ^1.0.0

**Comment by gpdeedler** [comment]
When using the latest builds of material-ui you access it with @material-ui / core not with material-ui.  So the forward slash "core" is now missing...

**Comment by leMaik** [comment]
@gpdeedler Sorry, I don't get it.
